apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim # rename
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi