apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  selector:
    app: influxdb
  ports:
  - protocol: TCP
    name: influxdb
    port: 8086
    targetPort: 8086
