apiVersion: v1
kind: PersistentVolume # аналог нод в самом кластере Kubernetes. Один PV может использоваться только одним PVС
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/mnt/mysql"
    type: DirectoryOrCreate
  claimRef:
    name: mysql-pvc
    namespace: default