{
 "title": "Grafana",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Memory_usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io.kubernetes.container.name", "operator": "=", "value": "grafana" }
     ]
    }
   ]
  },
  {
   "title": "CPU_usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io.kubernetes.container.name", "operator": "=", "value": "grafana" }
     ]
    }
   ]
  },
  {
   "title": "Pid",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_status",
     "select": [
      [
       { "params": [ "pid" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "io.kubernetes.container.name", "operator": "=", "value": "grafana" }
     ]
    }
   ]
  }
 ]
}