apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
  labels:
    app: grafana
  name: grafana
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 192.168.99.201
  selector:
    app: grafana
  ports:
  - port: 3000
    name: grafana
    protocol: TCP
    targetPort: 3000
status:
  loadBalancer: {}
