apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
  labels:
    app: wp
spec:
  externalTrafficPolicy: Cluster
  selector:
    app: wp
  type: LoadBalancer
  loadBalancerIP: 192.168.99.201
  ports:
    - protocol: TCP
      name: wp
      port: 5050
      targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp
  labels:
    app: wp
spec:
  selector:
    matchLabels:
      app: wp
  template:
    metadata:
      labels:
        app: wp
    spec:
      containers:
      - name: wp
        image: wp_image
        imagePullPolicy: Never
        ports:
        - containerPort: 5050