apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
  labels:
    app: ftps
  name: ftps
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 192.168.99.201
  selector:
    app: ftps
  ports:
  - name: ftps-connect              # установить соединение
    protocol: TCP
    port: 50021
    targetPort: 50021
  - name: data-transfer             # передача данных
    protocol: TCP
    port: 21
    targetPort: 21
